# Generated by Django 3.1.3 on 2020-12-27 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0007_auto_20201225_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_team1', to='teams.team')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_team2', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='WideReceiverStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('receptions', models.IntegerField(blank=True, default=0, null=True)),
                ('reception_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('touchdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('two_point_conversions', models.IntegerField(blank=True, default=0, null=True)),
                ('fumbles_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TightEndStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptions', models.IntegerField(blank=True, default=0, null=True)),
                ('reception_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('touchdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('two_point_conversions', models.IntegerField(blank=True, default=0, null=True)),
                ('fumbles_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunningBackStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rushing_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('receptions', models.IntegerField(blank=True, default=0, null=True)),
                ('reception_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('touchdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('two_point_conversions', models.IntegerField(blank=True, default=0, null=True)),
                ('fumbles_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuarterbackStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('pass_completions', models.IntegerField(blank=True, default=0, null=True)),
                ('pass_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('touchdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('two_point_conversions', models.IntegerField(blank=True, default=0, null=True)),
                ('interceptions', models.IntegerField(blank=True, default=0, null=True)),
                ('fumbles_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('rushing_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('rush_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KickReturnStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('return_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('fumbles', models.IntegerField(blank=True, default=0, null=True)),
                ('touchdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KickOffStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tackles', models.IntegerField(blank=True, default=0, null=True)),
                ('forced_fumbles', models.IntegerField(blank=True, default=0, null=True)),
                ('fumble_recovery', models.IntegerField(blank=True, default=0, null=True)),
                ('touchdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KickerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_points', models.IntegerField(blank=True, default=0, null=True)),
                ('field_goal_attempts', models.IntegerField(blank=True, default=0, null=True)),
                ('field_goals', models.IntegerField(blank=True, default=0, null=True)),
                ('two_points', models.IntegerField(blank=True, default=0, null=True)),
                ('tackles', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DefenseStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tackles', models.IntegerField(blank=True, default=0, null=True)),
                ('tackles_for_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('pass_break_ups', models.IntegerField(blank=True, default=0, null=True)),
                ('interceptions', models.IntegerField(blank=True, default=0, null=True)),
                ('force_fumbles', models.IntegerField(blank=True, default=0, null=True)),
                ('fumble_recovery', models.IntegerField(blank=True, default=0, null=True)),
                ('sacks', models.IntegerField(blank=True, default=0, null=True)),
                ('qb_hurries', models.IntegerField(blank=True, default=0, null=True)),
                ('touchdowns', models.IntegerField(blank=True, default=0, null=True)),
                ('fumble_return_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('interception_return_yardage', models.IntegerField(blank=True, default=0, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.game')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
