# Generated by Django 3.1.3 on 2021-04-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defensestat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='defensestat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='kickerstat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='kickerstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='kickoffstat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='kickoffstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='kickreturnstat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='kickreturnstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='quarterbackstat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='quarterbackstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='runningbackstat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='runningbackstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='tightendstat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='tightendstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='widereceiverstat',
            name='game',
        ),
        migrations.RemoveField(
            model_name='widereceiverstat',
            name='player',
        ),
        migrations.AddField(
            model_name='defensestat',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='defensestat',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kickerstat',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kickerstat',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kickoffstat',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kickoffstat',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kickreturnstat',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kickreturnstat',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quarterbackstat',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='quarterbackstat',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='runningbackstat',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='runningbackstat',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tightendstat',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tightendstat',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='widereceiverstat',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='widereceiverstat',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
