# Generated by Django 3.1.3 on 2020-12-01 00:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20201130_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='page_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
