# Generated by Django 3.1.3 on 2020-12-26 00:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_card_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_card_photos'),
        ),
        migrations.AlterField(
            model_name='team',
            name='page_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='teamgroup',
            name='page_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
