# Generated by Django 3.1.3 on 2020-12-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20201225_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
