# Generated by Django 3.1.3 on 2020-12-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20201227_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('TS', 'Test')], default='TS', max_length=2),
        ),
    ]
