# Generated by Django 3.1.3 on 2021-01-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_teamsocialmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamGroupTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('team_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teamgroup')),
            ],
        ),
        migrations.CreateModel(
            name='TeamGroupSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('team_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teamgroup')),
            ],
        ),
    ]
