# Generated by Django 3.1.3 on 2021-01-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_teamgroupsocialmedia_teamgroupticker_teamticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamgroupsocialmedia',
            name='team_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='teams.teamgroup'),
        ),
        migrations.AlterField(
            model_name='teamgroupticker',
            name='team_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='teams.teamgroup'),
        ),
        migrations.AlterField(
            model_name='teamsocialmedia',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='teamticker',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='teams.team'),
        ),
    ]
