# Generated by Django 3.1.3 on 2021-02-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210114_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
